name: Startup Cult Berlin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.09405624703504145
  lightness: 0.061290608486160636
  saturation: 0.8916140054352582
  rhythmicContrast: 0.5930201185401529
purpose: []
